# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEBaoBJKSxhGPCmCNPwNi2ydzB_o3t-3
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Canny edge detector function
def detect_edges(image, low_threshold=40, high_threshold=90):
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray_image, low_threshold, high_threshold)
    return edges

# Hough Line detection function
def detect_lines(edge_image, threshold=15, min_line_length=20, max_line_gap=15):
    lines = cv2.HoughLinesP(edge_image, 1, np.pi / 180, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)
    line_image = np.zeros((edge_image.shape[0], edge_image.shape[1], 3), dtype=np.uint8)

    if lines is not None:
        for line in lines:
            for x1, y1, x2, y2 in line:
                cv2.line(line_image, (x1, y1), (x2, y2), (0, 255, 0), 2)

    return line_image, lines

# Function to compute line orientation histograms
def compute_line_orientation_histogram(lines):
    num_bins = 72  # 360/5 = 72 bins for 5-degree intervals
    orientations = np.linspace(-180, 180, num_bins + 1)
    histogram = np.zeros(num_bins)

    if lines is None:
        return histogram, orientations

    for line in lines:
        for x1, y1, x2, y2 in line:
            angle = np.degrees(np.arctan2(y2 - y1, x2 - x1))
            angle = (angle + 180) % 360 - 180  # Normalize angle to the range [-180, 180)
            bin_idx = int((angle + 180) // (360 / num_bins))  # Find the corresponding bin
            line_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
            histogram[bin_idx] += line_length  # Weight by line length

    return histogram, orientations[:-1]

# Upload image file using Colab file upload
uploaded_files = files.upload()
image_path = next(iter(uploaded_files.keys()))

# Read the uploaded image
image = cv2.imread(image_path)

if image is None:
    print("Error: The image could not be loaded. Please try again.")
else:
    # Perform edge detection and line detection
    edge_image = detect_edges(image)
    line_image, lines = detect_lines(edge_image)
    histogram, orientations = compute_line_orientation_histogram(lines)

    # Display the results
    plt.figure(figsize=(15, 5))

    # Original image
    plt.subplot(1, 3, 1)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title('Original Image')
    plt.axis('off')

    # Edge detected image
    plt.subplot(1, 3, 2)
    plt.imshow(edge_image, cmap='gray')
    plt.title('Edge Detected Image')
    plt.axis('off')

    # Line detection result
    plt.subplot(1, 3, 3)
    plt.imshow(line_image)
    plt.title('Line Detection Result')
    plt.axis('off')

    plt.tight_layout()
    plt.show()

    # Plot line orientation histogram
    plt.figure(figsize=(10, 4))
    plt.bar(orientations, histogram, width=5, color='blue')  # Adjust the bar width to 5 degrees
    plt.title('Line Orientation Histogram (5 Degree Intervals)')
    plt.xlabel('Orientation (Degrees)')
    plt.ylabel('Accumulated Line Length')
    plt.xticks(orientations[::6])  # Show a tick every 30 degrees for clarity
    plt.xlim([-180, 180])
    plt.show()

import cv2
import numpy as np
import os
from scipy.spatial import distance
import matplotlib.pyplot as plt

# Edge detection using Canny
def detect_edges(image, low_thresh=40, high_thresh=80):
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edge_image = cv2.Canny(grayscale_image, low_thresh, high_thresh)
    return edge_image

# Line detection using Hough Transform
def detect_lines(edge_image, threshold=40, min_line_length=10, max_line_gap=10):
    lines_detected = cv2.HoughLinesP(edge_image, 1, np.pi / 180, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)
    return lines_detected

# Calculate orientation histogram (20-degree intervals)
def calculate_orientation_histogram(lines_detected, bins=18):  # 360/20 = 18 bins
    orientation_histogram = np.zeros(bins)
    if lines_detected is not None:
        for line in lines_detected:
            for x1, y1, x2, y2 in line:
                angle_deg = np.degrees(np.arctan2(y2 - y1, x2 - x1))
                angle_deg = (angle_deg + 180) % 360 - 180  # Normalize angle to [-180, 180)
                bin_idx = int((angle_deg + 180) // (360 / bins))  # Find the corresponding bin
                line_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
                orientation_histogram[bin_idx] += line_length  # Weight by line length
    return orientation_histogram

# Shift histogram circularly
def circular_shift_histogram(histogram, shift_amount):
    return np.roll(histogram, shift_amount)

# Find the best match between rotated and original histograms
def find_best_match(rotated_histogram, original_histograms, degree_interval=20):
    num_bins = len(rotated_histogram)
    best_match_idx, best_shift, min_distance = -1, 0, float('inf')

    for shift in range(num_bins):
        shifted_histogram = circular_shift_histogram(rotated_histogram, shift)
        for idx, original_histogram in enumerate(original_histograms):
            dist = distance.euclidean(shifted_histogram, original_histogram)
            if dist < min_distance:
                min_distance = dist
                best_match_idx = idx
                best_shift = shift

    rotation_angle = -best_shift * degree_interval % 360
    return best_match_idx, rotation_angle, min_distance

# Supported image formats
supported_formats = (".jpg", ".jpeg", ".png", ".bmp", ".tiff")

# Load original images and compute histograms
original_histograms = []
original_images_dir = '/content/extracted/img'
if not os.path.exists(original_images_dir):
    print(f"Error: Directory '{original_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(original_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        image_path = os.path.join(original_images_dir, filename)
        print(f"Processing original image: {image_path}")

        # Read the image and check if it's loaded successfully
        image = cv2.imread(image_path)
        if image is None:
            print(f"Error: Unable to load image at {image_path}. Please check the file path or format.")
            continue

        # Process the image
        edges = detect_edges(image)
        lines = detect_lines(edges)
        histogram = calculate_orientation_histogram(lines)
        original_histograms.append(histogram)

# Process rotated images
def process_rotated_image(rotated_image_path, original_histograms):
    rotated_image = cv2.imread(rotated_image_path)
    if rotated_image is None:
        print(f"Error: Unable to load rotated image at {rotated_image_path}.")
        return None, None, None

    edges = detect_edges(rotated_image)
    lines = detect_lines(edges)
    rotated_histogram = calculate_orientation_histogram(lines)

    # Ensure rotated_histogram is a valid array
    if rotated_histogram is None or not isinstance(rotated_histogram, np.ndarray):
        print(f"Error: Failed to compute histogram for {rotated_image_path}.")
        return None, None, None

    best_match_idx, rotation_angle, _ = find_best_match(rotated_histogram, original_histograms)
    return best_match_idx, rotation_angle, rotated_histogram

rotated_images_dir = '/content/extracted/rotated_img_new'
if not os.path.exists(rotated_images_dir):
    print(f"Error: Directory '{rotated_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(rotated_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        rotated_image_path = os.path.join(rotated_images_dir, filename)
        print(f"Processing rotated image: {rotated_image_path}")

        best_match_idx, rotation_angle, rotated_histogram = process_rotated_image(rotated_image_path, original_histograms)
        if rotated_histogram is None:
            print(f"Error processing rotated image: {filename}")
            continue

       # print(f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees.")

        # Visualize histograms
        def plot_histogram(histogram, title, subtitle=None):
            if histogram is None or not isinstance(histogram, np.ndarray):
                print(f"Invalid histogram provided for plotting: {title}")
                return
            plt.figure(figsize=(10, 4))
            plt.bar(np.arange(len(histogram)), histogram, width=1, color='blue')
            plt.title(title)
            if subtitle:
                plt.suptitle(subtitle, fontsize=10, color="red")
            plt.xlabel('Orientation (Degrees)')
            plt.ylabel('Accumulated line length')
            plt.xticks(np.arange(0, 18), labels=[f"{i*20}" for i in range(0, 18)])  # Labels every 20 degrees
            plt.xlim([0, 17])
            plt.show()

        # Plot histograms for the matched images
        subtitle_text = f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees."
        plot_histogram(original_histograms[best_match_idx], 'Original Image Histogram (20 Degree Intervals)', subtitle=subtitle_text)
        plot_histogram(rotated_histogram, 'Rotated Image Histogram (20 Degree Intervals)', subtitle=subtitle_text)

import cv2
import numpy as np
import os
from scipy.spatial import distance
import matplotlib.pyplot as plt

# Edge detection using Canny
def detect_edges(image, low_thresh=40, high_thresh=80):
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edge_image = cv2.Canny(grayscale_image, low_thresh, high_thresh)
    return edge_image

# Line detection using Hough Transform
def detect_lines(edge_image, threshold=40, min_line_length=10, max_line_gap=10):
    lines_detected = cv2.HoughLinesP(edge_image, 1, np.pi / 180, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)
    return lines_detected

# Calculate orientation histogram (10-degree intervals)
def calculate_orientation_histogram(lines_detected, bins=36):  # 360/10 = 36 bins
    orientation_histogram = np.zeros(bins)
    if lines_detected is not None:
        for line in lines_detected:
            for x1, y1, x2, y2 in line:
                angle_deg = np.degrees(np.arctan2(y2 - y1, x2 - x1))
                angle_deg = (angle_deg + 180) % 360 - 180  # Normalize angle to [-180, 180)
                bin_idx = int((angle_deg + 180) // (360 / bins))  # Find the corresponding bin
                line_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
                orientation_histogram[bin_idx] += line_length  # Weight by line length
    return orientation_histogram

# Shift histogram circularly
def circular_shift_histogram(histogram, shift_amount):
    return np.roll(histogram, shift_amount)

# Find the best match between rotated and original histograms
def find_best_match(rotated_histogram, original_histograms, degree_interval=10):
    num_bins = len(rotated_histogram)
    best_match_idx, best_shift, min_distance = -1, 0, float('inf')

    for shift in range(num_bins):
        shifted_histogram = circular_shift_histogram(rotated_histogram, shift)
        for idx, original_histogram in enumerate(original_histograms):
            dist = distance.euclidean(shifted_histogram, original_histogram)
            if dist < min_distance:
                min_distance = dist
                best_match_idx = idx
                best_shift = shift

    rotation_angle = -best_shift * degree_interval % 360
    return best_match_idx, rotation_angle, min_distance

# Supported image formats
supported_formats = (".jpg", ".jpeg", ".png", ".bmp", ".tiff")

# Load original images and compute histograms
original_histograms = []
original_images_dir = '/content/extracted/img'
if not os.path.exists(original_images_dir):
    print(f"Error: Directory '{original_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(original_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        image_path = os.path.join(original_images_dir, filename)
        print(f"Processing original image: {image_path}")

        # Read the image and check if it's loaded successfully
        image = cv2.imread(image_path)
        if image is None:
            print(f"Error: Unable to load image at {image_path}. Please check the file path or format.")
            continue

        # Process the image
        edges = detect_edges(image)
        lines = detect_lines(edges)
        histogram = calculate_orientation_histogram(lines)
        original_histograms.append(histogram)

# Process rotated images
def process_rotated_image(rotated_image_path, original_histograms):
    rotated_image = cv2.imread(rotated_image_path)
    if rotated_image is None:
        print(f"Error: Unable to load rotated image at {rotated_image_path}.")
        return None, None, None

    edges = detect_edges(rotated_image)
    lines = detect_lines(edges)
    rotated_histogram = calculate_orientation_histogram(lines)

    # Ensure rotated_histogram is a valid array
    if rotated_histogram is None or not isinstance(rotated_histogram, np.ndarray):
        print(f"Error: Failed to compute histogram for {rotated_image_path}.")
        return None, None, None

    best_match_idx, rotation_angle, _ = find_best_match(rotated_histogram, original_histograms, degree_interval=10)
    return best_match_idx, rotation_angle, rotated_histogram

rotated_images_dir = '/content/extracted/rotated_img_new'
if not os.path.exists(rotated_images_dir):
    print(f"Error: Directory '{rotated_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(rotated_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        rotated_image_path = os.path.join(rotated_images_dir, filename)
        print(f"Processing rotated image: {rotated_image_path}")

        best_match_idx, rotation_angle, rotated_histogram = process_rotated_image(rotated_image_path, original_histograms)
        if rotated_histogram is None:
            print(f"Error processing rotated image: {filename}")
            continue

        print(f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees.")

        # Visualize histograms
        def plot_histogram(histogram, title, subtitle=None):
            if histogram is None or not isinstance(histogram, np.ndarray):
                print(f"Invalid histogram provided for plotting: {title}")
                return
            plt.figure(figsize=(10, 4))
            plt.bar(np.arange(len(histogram)), histogram, width=1, color='blue')
            plt.title(title)
            if subtitle:
                plt.suptitle(subtitle, fontsize=10, color="red")
            plt.xlabel('Orientation (Degrees)')
            plt.ylabel('Accumulated line length')
            plt.xticks(np.arange(0, 36), labels=[f"{i*10}" for i in range(0, 36)])  # Labels every 10 degrees
            plt.xlim([0, 35])
            plt.show()

        # Plot histograms for the matched images
        subtitle_text = f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees."
        plot_histogram(original_histograms[best_match_idx], 'Original Image Histogram (10 Degree Intervals)', subtitle=subtitle_text)
        plot_histogram(rotated_histogram, 'Rotated Image Histogram (10 Degree Intervals)', subtitle=subtitle_text)

import cv2
import numpy as np
import os
from scipy.spatial import distance
import matplotlib.pyplot as plt

# Edge detection using Canny
def detect_edges(image, low_thresh=40, high_thresh=80):
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edge_image = cv2.Canny(grayscale_image, low_thresh, high_thresh)
    return edge_image

# Line detection using Hough Transform
def detect_lines(edge_image, threshold=40, min_line_length=10, max_line_gap=10):
    lines_detected = cv2.HoughLinesP(edge_image, 1, np.pi / 180, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)
    return lines_detected

# Calculate orientation histogram (5-degree intervals)
def calculate_orientation_histogram(lines_detected, bins=72):  # 360/5 = 72 bins
    orientation_histogram = np.zeros(bins)
    if lines_detected is not None:
        for line in lines_detected:
            for x1, y1, x2, y2 in line:
                angle_deg = np.degrees(np.arctan2(y2 - y1, x2 - x1))
                angle_deg = (angle_deg + 180) % 360 - 180  # Normalize angle to [-180, 180)
                bin_idx = int((angle_deg + 180) // (360 / bins))  # Find the corresponding bin
                line_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
                orientation_histogram[bin_idx] += line_length  # Weight by line length
    return orientation_histogram

# Shift histogram circularly
def circular_shift_histogram(histogram, shift_amount):
    return np.roll(histogram, shift_amount)

# Find the best match between rotated and original histograms
def find_best_match(rotated_histogram, original_histograms, degree_interval=5):
    num_bins = len(rotated_histogram)
    best_match_idx, best_shift, min_distance = -1, 0, float('inf')

    for shift in range(num_bins):
        shifted_histogram = circular_shift_histogram(rotated_histogram, shift)
        for idx, original_histogram in enumerate(original_histograms):
            dist = distance.euclidean(shifted_histogram, original_histogram)
            if dist < min_distance:
                min_distance = dist
                best_match_idx = idx
                best_shift = shift

    rotation_angle = -best_shift * degree_interval % 360
    return best_match_idx, rotation_angle, min_distance

# Supported image formats
supported_formats = (".jpg", ".jpeg", ".png", ".bmp", ".tiff")

# Load original images and compute histograms
original_histograms = []
original_images_dir = '/content/extracted/img'
if not os.path.exists(original_images_dir):
    print(f"Error: Directory '{original_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(original_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        image_path = os.path.join(original_images_dir, filename)
        print(f"Processing original image: {image_path}")

        # Read the image and check if it's loaded successfully
        image = cv2.imread(image_path)
        if image is None:
            print(f"Error: Unable to load image at {image_path}. Please check the file path or format.")
            continue

        # Process the image
        edges = detect_edges(image)
        lines = detect_lines(edges)
        histogram = calculate_orientation_histogram(lines)
        original_histograms.append(histogram)

# Process rotated images
def process_rotated_image(rotated_image_path, original_histograms):
    rotated_image = cv2.imread(rotated_image_path)
    if rotated_image is None:
        print(f"Error: Unable to load rotated image at {rotated_image_path}.")
        return None, None, None

    edges = detect_edges(rotated_image)
    lines = detect_lines(edges)
    rotated_histogram = calculate_orientation_histogram(lines)

    # Ensure rotated_histogram is a valid array
    if rotated_histogram is None or not isinstance(rotated_histogram, np.ndarray):
        print(f"Error: Failed to compute histogram for {rotated_image_path}.")
        return None, None, None

    best_match_idx, rotation_angle, _ = find_best_match(rotated_histogram, original_histograms, degree_interval=5)
    return best_match_idx, rotation_angle, rotated_histogram

rotated_images_dir = '/content/extracted/rotated_img_new'
if not os.path.exists(rotated_images_dir):
    print(f"Error: Directory '{rotated_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(rotated_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        rotated_image_path = os.path.join(rotated_images_dir, filename)
        print(f"Processing rotated image: {rotated_image_path}")

        best_match_idx, rotation_angle, rotated_histogram = process_rotated_image(rotated_image_path, original_histograms)
        if rotated_histogram is None:
            print(f"Error processing rotated image: {filename}")
            continue

        print(f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees.")

        # Visualize histograms
        def plot_histogram(histogram, title, subtitle=None):
            if histogram is None or not isinstance(histogram, np.ndarray):
                print(f"Invalid histogram provided for plotting: {title}")
                return
            plt.figure(figsize=(10, 4))
            plt.bar(np.arange(len(histogram)), histogram, width=1, color='blue')
            plt.title(title)
            if subtitle:
                plt.suptitle(subtitle, fontsize=10, color="red")
            plt.xlabel('Orientation (Degrees)')
            plt.ylabel('Accumulated line length')
            plt.xticks(np.arange(0, 72, 2), labels=[f"{i*5}" for i in range(0, 72, 2)])  # Labels every 10 degrees for clarity
            plt.xlim([0, 71])
            plt.show()

        # Plot histograms for the matched images
        subtitle_text = f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees."
        plot_histogram(original_histograms[best_match_idx], 'Original Image Histogram (5 Degree Intervals)', subtitle=subtitle_text)
        plot_histogram(rotated_histogram, 'Rotated Image Histogram (5 Degree Intervals)', subtitle=subtitle_text)

import cv2
import numpy as np
import os
from scipy.spatial import distance
import matplotlib.pyplot as plt

# Edge detection using Canny
def detect_edges(image, low_thresh=40, high_thresh=80):
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edge_image = cv2.Canny(grayscale_image, low_thresh, high_thresh)
    return edge_image

# Line detection using Hough Transform
def detect_lines(edge_image, threshold=40, min_line_length=10, max_line_gap=10):
    lines_detected = cv2.HoughLinesP(edge_image, 1, np.pi / 180, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)
    return lines_detected

# Calculate orientation histogram (1-degree intervals)
def calculate_orientation_histogram(lines_detected, bins=360):  # 360/1 = 360 bins
    orientation_histogram = np.zeros(bins)
    if lines_detected is not None:
        for line in lines_detected:
            for x1, y1, x2, y2 in line:
                angle_deg = np.degrees(np.arctan2(y2 - y1, x2 - x1))
                angle_deg = (angle_deg + 180) % 360 - 180  # Normalize angle to [-180, 180)
                bin_idx = int((angle_deg + 180) // (360 / bins))  # Find the corresponding bin
                line_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
                orientation_histogram[bin_idx] += line_length  # Weight by line length
    return orientation_histogram

# Shift histogram circularly
def circular_shift_histogram(histogram, shift_amount):
    return np.roll(histogram, shift_amount)

# Find the best match between rotated and original histograms
def find_best_match(rotated_histogram, original_histograms, degree_interval=1):
    num_bins = len(rotated_histogram)
    best_match_idx, best_shift, min_distance = -1, 0, float('inf')

    for shift in range(num_bins):
        shifted_histogram = circular_shift_histogram(rotated_histogram, shift)
        for idx, original_histogram in enumerate(original_histograms):
            dist = distance.euclidean(shifted_histogram, original_histogram)
            if dist < min_distance:
                min_distance = dist
                best_match_idx = idx
                best_shift = shift

    rotation_angle = -best_shift * degree_interval % 360
    return best_match_idx, rotation_angle, min_distance

# Supported image formats
supported_formats = (".jpg", ".jpeg", ".png", ".bmp", ".tiff")

# Load original images and compute histograms
original_histograms = []
original_images_dir = '/content/extracted/img'
if not os.path.exists(original_images_dir):
    print(f"Error: Directory '{original_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(original_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        image_path = os.path.join(original_images_dir, filename)
        print(f"Processing original image: {image_path}")

        # Read the image and check if it's loaded successfully
        image = cv2.imread(image_path)
        if image is None:
            print(f"Error: Unable to load image at {image_path}. Please check the file path or format.")
            continue

        # Process the image
        edges = detect_edges(image)
        lines = detect_lines(edges)
        histogram = calculate_orientation_histogram(lines)
        original_histograms.append(histogram)

# Process rotated images
def process_rotated_image(rotated_image_path, original_histograms):
    rotated_image = cv2.imread(rotated_image_path)
    if rotated_image is None:
        print(f"Error: Unable to load rotated image at {rotated_image_path}.")
        return None, None, None

    edges = detect_edges(rotated_image)
    lines = detect_lines(edges)
    rotated_histogram = calculate_orientation_histogram(lines)

    # Ensure rotated_histogram is a valid array
    if rotated_histogram is None or not isinstance(rotated_histogram, np.ndarray):
        print(f"Error: Failed to compute histogram for {rotated_image_path}.")
        return None, None, None

    best_match_idx, rotation_angle, _ = find_best_match(rotated_histogram, original_histograms, degree_interval=1)
    return best_match_idx, rotation_angle, rotated_histogram

rotated_images_dir = '/content/extracted/rotated_img_new'
if not os.path.exists(rotated_images_dir):
    print(f"Error: Directory '{rotated_images_dir}' does not exist. Please check the extraction.")
else:
    for filename in sorted(os.listdir(rotated_images_dir)):
        if not filename.lower().endswith(supported_formats):
            print(f"Skipping unsupported file: {filename}")
            continue

        rotated_image_path = os.path.join(rotated_images_dir, filename)
        print(f"Processing rotated image: {rotated_image_path}")

        best_match_idx, rotation_angle, rotated_histogram = process_rotated_image(rotated_image_path, original_histograms)
        if rotated_histogram is None:
            print(f"Error processing rotated image: {filename}")
            continue

        print(f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees.")

        # Visualize histograms
        def plot_histogram(histogram, title, subtitle=None):
            if histogram is None or not isinstance(histogram, np.ndarray):
                print(f"Invalid histogram provided for plotting: {title}")
                return
            plt.figure(figsize=(12, 5))
            plt.bar(np.arange(len(histogram)), histogram, width=1, color='blue')
            plt.title(title)
            if subtitle:
                plt.suptitle(subtitle, fontsize=10, color="red")
            plt.xlabel('Orientation (Degrees)')
            plt.ylabel('Accumulated line length')
            plt.xticks(np.arange(0, 360, 30), labels=[f"{i}" for i in range(0, 360, 30)])  # Labels every 30 degrees for clarity
            plt.xlim([0, 359])
            plt.show()

        # Plot histograms for the matched images
        subtitle_text = f"Rotated image '{filename}' matches with original image index {best_match_idx} with an estimated rotation angle of {rotation_angle} degrees."
        plot_histogram(original_histograms[best_match_idx], 'Original Image Histogram (1 Degree Intervals)', subtitle=subtitle_text)
        plot_histogram(rotated_histogram, 'Rotated Image Histogram (1 Degree Intervals)', subtitle=subtitle_text)