# -*- coding: utf-8 -*-
"""CS484_HW2_Part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyr9ZLAFMjAq41MjFj6Ubvwlf3_Csral
"""

# Import necessary libraries
import os
import zipfile
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.segmentation import slic, mark_boundaries
from skimage.util import img_as_float
from google.colab import files

# Function to unzip uploaded files
def extract_zip(upload_path, extract_to):
    with zipfile.ZipFile(upload_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to)

# Upload and unzip images
print("Please upload your zip file containing images.")
uploaded = files.upload()
for filename in uploaded.keys():
    extract_zip(filename, '/content/images')

# Function to load images from a directory
def load_images_from_folder(folder):
    images = []
    filenames = []
    for filename in os.listdir(folder):
        if filename.endswith(".jpg"):
            img = cv2.imread(os.path.join(folder, filename))
            if img is not None:
                images.append(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  # Convert to RGB for visualization
                filenames.append(filename)
    return images, filenames

# Function to generate superpixels using SLIC
def generate_superpixels(img, n_segments=100, compactness=10):
    img_float = img_as_float(img)
    labels = slic(img_float, n_segments=n_segments, compactness=compactness, start_label=1)
    return labels

# Main workflow
image_dir = '/content/images'
images, filenames = load_images_from_folder(image_dir)

# Parameters for SLIC
n_segments = 100  # Number of superpixels
compactness = 10  # Compactness parameter for SLIC

# Perform superpixel segmentation and visualize results
output_dir = '/content/output_superpixels'
os.makedirs(output_dir, exist_ok=True)

print("Performing superpixel segmentation...")
for img, fname in zip(images, filenames):
    # Generate superpixels
    labels = generate_superpixels(img, n_segments=n_segments, compactness=compactness)

    # Visualize the boundaries
    segmented_image = mark_boundaries(img, labels, color=(1, 0, 0))

    # Save the result
    output_path = os.path.join(output_dir, f"{os.path.splitext(fname)[0]}_superpixels.png")
    plt.figure(figsize=(10, 10))
    plt.imshow(segmented_image)
    plt.title(f"Superpixels for {fname}")
    plt.axis("off")
    plt.savefig(output_path, bbox_inches='tight')
    plt.show()

print("Superpixel results have been saved to:", output_dir)

# Import necessary libraries
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.segmentation import slic, mark_boundaries
from skimage.util import img_as_float

# Function to load images from a directory
def load_images_from_folder(folder):
    images = []
    filenames = []
    for filename in os.listdir(folder):
        if filename.endswith(".jpg"):
            img = cv2.imread(os.path.join(folder, filename))
            if img is not None:
                images.append(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  # Convert to RGB for visualization
                filenames.append(filename)
    return images, filenames

# Function to generate superpixels using SLIC
def generate_superpixels(img, n_segments=100, compactness=10):
    labels = slic(img_as_float(img), n_segments=n_segments, compactness=compactness, start_label=1)
    return labels

# Function to create a bank of Gabor filters
def create_gabor_filter_bank(scales, orientations):
    filters = []
    for scale in scales:
        for orientation in orientations:
            kernel = cv2.getGaborKernel((21, 21), 4.0, orientation, scale, 1, 0, ktype=cv2.CV_32F)
            filters.append(kernel)
    return filters

# Function to compute Gabor responses
def compute_gabor_responses(img, gabor_filters):
    responses = []
    for kernel in gabor_filters:
        response = cv2.filter2D(img, cv2.CV_32F, kernel)
        responses.append(np.abs(response))  # Use the magnitude of the response
    return responses

# Main workflow
image_dir = '/content/images'  # Path where your images are stored
images, filenames = load_images_from_folder(image_dir)

# Parameters for SLIC
n_segments = 200  # Increase the number of superpixels for more detail
compactness = 20  # Adjust compactness for more regular superpixels

# Parameters for Gabor filter bank
scales = [4, 8, 16, 32]  # 4 scales
orientations = [0, np.pi/4, np.pi/2, 3*np.pi/4]  # 4 orientations

# Create Gabor filter bank
gabor_filters = create_gabor_filter_bank(scales, orientations)

# Perform processing and visualize results
output_dir = '/content/output_superpixels_and_gabor'
os.makedirs(output_dir, exist_ok=True)

print("Performing superpixel segmentation and Gabor feature extraction...")
for img, fname in zip(images, filenames):
    # Convert image to grayscale
    gray_img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # Generate superpixels
    labels = generate_superpixels(img, n_segments=n_segments, compactness=compactness)

    # Visualize superpixel boundaries
    segmented_image = mark_boundaries(img, labels, color=(1, 0, 0))

    # Compute Gabor responses
    gabor_responses = compute_gabor_responses(gray_img, gabor_filters)

    # Visualize Gabor responses for the first scale and orientation
    plt.figure(figsize=(10, 10))
    plt.subplot(1, 2, 1)
    plt.imshow(segmented_image)
    plt.title(f"Superpixels for {fname}")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(gabor_responses[0], cmap='gray')
    plt.title(f"Gabor Response (Scale={scales[0]}, Orientation={orientations[0]})")
    plt.axis("off")

    # Save visualization
    output_path = os.path.join(output_dir, f"{os.path.splitext(fname)[0]}_superpixels_and_gabor.png")
    plt.savefig(output_path, bbox_inches='tight')
    plt.show()

    print(f"Results saved for {fname}: {output_path}")

print("Superpixel segmentation and Gabor feature visualization completed.")

# Import necessary libraries
import os
import cv2
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from skimage.segmentation import slic, mark_boundaries
from skimage.util import img_as_float

# Function to load images from a directory
def load_images_from_folder(folder):
    images = []
    filenames = []
    for filename in os.listdir(folder):
        if filename.endswith(".jpg"):
            img = cv2.imread(os.path.join(folder, filename))
            if img is not None:
                images.append(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  # Convert to RGB for visualization
                filenames.append(filename)
    return images, filenames

# Function to generate superpixels using SLIC
def generate_superpixels(img, n_segments=100, compactness=10):
    labels = slic(img_as_float(img), n_segments=n_segments, compactness=compactness, start_label=1)
    return labels

# Function to create a bank of Gabor filters
def create_gabor_filter_bank(scales, orientations):
    filters = []
    for scale in scales:
        for orientation in orientations:
            kernel = cv2.getGaborKernel((21, 21), 4.0, orientation, scale, 1, 0, ktype=cv2.CV_32F)
            filters.append(kernel)
    return filters

# Function to compute Gabor responses
def compute_gabor_responses(img, gabor_filters):
    responses = []
    for kernel in gabor_filters:
        response = cv2.filter2D(img, cv2.CV_32F, kernel)
        responses.append(np.abs(response))  # Use the magnitude of the response
    return responses

# Function to compute average Gabor features for superpixels
def compute_superpixel_gabor_features(labels, gabor_responses):
    unique_labels = np.unique(labels)
    features = []
    for label in unique_labels:
        mask = (labels == label)
        avg_features = [np.mean(response[mask]) for response in gabor_responses]
        features.append(avg_features)
    return np.array(features)

# Main workflow
image_dir = '/content/images'  # Path where your images are stored
images, filenames = load_images_from_folder(image_dir)

# Parameters for SLIC
n_segments = 200  # Number of superpixels
compactness = 20  # Compactness parameter for SLIC

# Parameters for Gabor filter bank
scales = [4, 8, 16, 32]  # 4 scales
orientations = [0, np.pi/4, np.pi/2, 3*np.pi/4]  # 4 orientations

# Create Gabor filter bank
gabor_filters = create_gabor_filter_bank(scales, orientations)

# Collect all superpixel features from all images
print("Extracting Gabor features and superpixels...")
all_features = []  # To store all superpixel features
all_labels = []  # To store superpixel labels for visualization
image_shapes = []  # To store the shape of each image for reconstruction

for img in images:
    # Convert image to grayscale
    gray_img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # Generate superpixels
    labels = generate_superpixels(img, n_segments=n_segments, compactness=compactness)
    all_labels.append(labels)
    image_shapes.append(labels.shape)

    # Compute Gabor responses
    gabor_responses = compute_gabor_responses(gray_img, gabor_filters)

    # Compute average Gabor features for each superpixel
    superpixel_features = compute_superpixel_gabor_features(labels, gabor_responses)
    all_features.append(superpixel_features)

# Flatten all features into a single matrix
all_features_flat = np.vstack(all_features)

# Perform K-Means Clustering
n_clusters = 10  # Number of clusters
print(f"Clustering {all_features_flat.shape[0]} superpixels into {n_clusters} clusters...")
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
cluster_labels = kmeans.fit_predict(all_features_flat)

# Visualize clustering results with pseudo-color images
output_dir = '/content/output_pseudo_color'
os.makedirs(output_dir, exist_ok=True)

print("Generating pseudo-color images...")
cluster_index = 0
colors = np.array(plt.colormaps['tab10'](np.linspace(0, 1, n_clusters)))[:, :3]  # Use only RGB values

for img, labels, shape, fname in zip(images, all_labels, image_shapes, filenames):
    pseudo_color_image = np.zeros((*shape, 3), dtype=np.uint8)
    unique_labels = np.unique(labels)

    for label in unique_labels:
        mask = (labels == label)
        cluster_color = (colors[cluster_labels[cluster_index]] * 255).astype(int)[:3]  # Ensure RGB only
        pseudo_color_image[mask] = cluster_color
        cluster_index += 1

    # Save pseudo-color image
    output_path = os.path.join(output_dir, f"{os.path.splitext(fname)[0]}_pseudo_color.png")
    plt.figure(figsize=(10, 10))
    plt.imshow(pseudo_color_image)
    plt.title(f"Pseudo-Color Clustering for {fname}")
    plt.axis("off")
    plt.savefig(output_path, bbox_inches='tight')
    plt.show()

print("Pseudo-color images have been saved to:", output_dir)

import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist

# Function to compute centroids of superpixels
def compute_superpixel_centroids(labels):
    unique_labels = np.unique(labels)
    centroids = []
    for label in unique_labels:
        mask = (labels == label)
        coords = np.argwhere(mask)
        centroid = np.mean(coords, axis=0)
        centroids.append(centroid)
    return np.array(centroids)

# Function to compute contextual features
def compute_contextual_features(features, labels, radius1, radius2):
    centroids = compute_superpixel_centroids(labels)
    contextual_features = []
    unique_labels = np.unique(labels)

    for idx, label in enumerate(unique_labels):
        mask = (labels == label)
        distances = cdist([centroids[idx]], centroids).flatten()

        # First-level neighbors
        neighbors1 = (distances > 0) & (distances <= radius1)
        features1 = features[neighbors1].mean(axis=0) if np.any(neighbors1) else np.zeros_like(features[0])

        # Second-level neighbors
        neighbors2 = (distances > radius1) & (distances <= radius2)
        features2 = features[neighbors2].mean(axis=0) if np.any(neighbors2) else np.zeros_like(features[0])

        # Concatenate features
        combined_features = np.concatenate([features[idx], features1, features2])
        contextual_features.append(combined_features)

    return np.array(contextual_features)

# Main workflow for contextual clustering
output_dir_contextual = '/content/output_contextual_pseudo_color'
os.makedirs(output_dir_contextual, exist_ok=True)

# Define parameters
radius1 = 1.5 * np.sqrt(images[0].shape[0] * images[0].shape[1] / n_segments)  # First-level neighborhood radius
radius2 = 2.5 * np.sqrt(images[0].shape[0] * images[0].shape[1] / n_segments)  # Second-level neighborhood radius

# Generate contextual features for all superpixels
print("Computing contextual features...")
contextual_features_list = []
contextual_labels = []
for img, labels, features in zip(images, all_labels, all_features):
    contextual_features = compute_contextual_features(features, labels, radius1, radius2)
    contextual_features_list.append(contextual_features)
    contextual_labels.append(labels)

# Flatten all contextual features for clustering
all_contextual_features = np.vstack(contextual_features_list)

# Perform K-Means Clustering
n_clusters = 10  # Number of clusters
print(f"Clustering {all_contextual_features.shape[0]} superpixels with contextual features into {n_clusters} clusters...")
kmeans_contextual = KMeans(n_clusters=n_clusters, random_state=42)
contextual_cluster_labels = kmeans_contextual.fit_predict(all_contextual_features)

# Visualize clustering results with pseudo-color images
print("Generating pseudo-color images with contextual features...")
cluster_index = 0
colors = np.array(plt.colormaps['tab10'](np.linspace(0, 1, n_clusters)))[:, :3]  # RGB values only

for img, labels, shape, fname in zip(images, contextual_labels, image_shapes, filenames):
    pseudo_color_image = np.zeros((*shape, 3), dtype=np.uint8)
    unique_labels = np.unique(labels)

    for label in unique_labels:
        mask = (labels == label)
        cluster_color = (colors[contextual_cluster_labels[cluster_index]] * 255).astype(int)
        pseudo_color_image[mask] = cluster_color
        cluster_index += 1

    # Save pseudo-color image
    output_path = os.path.join(output_dir_contextual, f"{os.path.splitext(fname)[0]}_contextual_pseudo_color.png")
    plt.figure(figsize=(10, 10))
    plt.imshow(pseudo_color_image)
    plt.title(f"Contextual Clustering for {fname}")
    plt.axis("off")
    plt.savefig(output_path, bbox_inches='tight')
    plt.show()

print("Contextual pseudo-color images have been saved to:", output_dir_contextual)